[package]
name = "edit_hints"
version = "0.1.0"
authors = ["Isaac Lozano <109lozanoi@gmail.com>"]

[dependencies]
sa2_text = {path = "../sa2_text"}
prs_util = {path = "../prs_util"}
serde_json = "1.0"
